<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-CIB1RGQG" failures="0" tests="3" name="PractiseForTestNg.TestForEnableTimeOutDeoendecies" time="0.226" errors="1" timestamp="17 Jan 2019 16:17:23 GMT" skipped="0">
  <testcase classname="PractiseForTestNg.TestForEnableTimeOutDeoendecies" name="Test2" time="0.005"/>
  <testcase classname="PractiseForTestNg.TestForEnableTimeOutDeoendecies" name="Test1" time="0.217">
    <error message="Method PractiseForTestNg.TestForEnableTimeOutDeoendecies.Test1() didn&#039;t finish within the time-out 200" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method PractiseForTestNg.TestForEnableTimeOutDeoendecies.Test1() didn't finish within the time-out 200
]]>
    </error>
  </testcase> <!-- Test1 -->
  <testcase classname="PractiseForTestNg.TestForEnableTimeOutDeoendecies" name="Test3" time="0.004"/>
</testsuite> <!-- PractiseForTestNg.TestForEnableTimeOutDeoendecies -->
